### ISSUE TITLE
[REQUEST] add AGAT to repo

### ISSUE THREAD

**Issue by kbipinkumar** [BioArchLinux/Packages#102]
**Information**
 - Package Name: AGAT
 - Can it directly run on Linux: [yes]
 - Can it run on the wine: [NA]
 - Website: https://github.com/NBISweden/AGAT
 - Download URL: https://github.com/NBISweden/AGAT
 - Package description: Another Gtf/Gff Analysis Toolkit is suite of tools to handle gene annotations in any GTF/GFF format.
 - DOI: https://www.doi.org/10.5281/zenodo.3552717
 

**Popularity**
 - Number of citations from WOS per year: [N/A]
 - Research interests in ResearchGate: [N/A]
 - Any other reason: the package is a pretty useful in fixing augustus hint gtf file formatting generated in BRAKER2 pipeline. furthermore the package seems to be in debian-med collection which, as per limited understanding, Bioarchlinux project is trying to add to repo.

**Additional information**
i was able to compile the package using [PKGBUILD here](https://gist.github.com/kbipinkumar/779ec184aeb3c6fa2b09e592f00c8d59). the upstream recommends following dependencies (i have converted ubuntu packages recommended in upstream repo to their equivalent in archlinux ecosystem)
1. perl-bioperl
2. perl-clone
3. perl-carp-clan
4. perl-sort-naturally
5. perl-yaml-libyaml
6. perl-lwp-protocol-https
7. perl-file-sharedir-install
8. perl-file-sharedir-install
9. perl-graph
10. perl-lwp-useragent-determined
11. perl-moose
12. perl-file-share
packages 9 to 12 are present only in AUR. therefore, those also will need to be added to repo along with their dependency, if any. (Any help in this regard would be valuable)

**Comment by starsareintherose** [comment]
Okay, I will check these and if you are delighted, use https://archlinux.org/packages/community/any/perl-cpanplus-dist-arch/ to produce Perl PKGBUILD.

These days I am busy working on PhD application.

**Comment by kbipinkumar** [comment]
so if i understand correctly, i can use `cpan2aur` utility to create PKGBUILD for the aforementioned dependencies and alongwith appropriate `lilac.yaml` can submitted to the repository as PR?

**Comment by starsareintherose** [comment]
Thanks, right
