### ISSUE TITLE
[MAINTAIN] ugene maintain

### ISSUE THREAD

**Issue by starsareintherose** [BioArchLinux/Packages#116]
**Log of the bug**

**Packages (please complete the following information):**
 - Package Name:  ugene

**Description**
Could @hubutui maintain ugene at this repo

**Comment by hubutui** [comment]
cool, I'm going to orphan ugen at archlinuxcn repo.

**Comment by starsareintherose** [comment]
Could you migrate it to thiss repo now?

**Comment by hubutui** [comment]
I don't use this pkg. It would be great if you continue to maintain it here. Thanks.

**Comment by starsareintherose** [comment]
Okay, but add BioArchLinuxBot as maintainer in AUR
