### ISSUE TITLE
Request -- Arrow with zstd support

### ISSUE THREAD

**Issue by bshor** [BioArchLinux/Packages#117]
Hello, thank you for including r-arrow in your repository. The compiled version lacks support for zstd, a newly-common compression format.

From the [documentation](https://arrow.apache.org/docs/r/articles/install.html), it appears you need to set an environment variable to get this support.

`Sys.setenv(ARROW_WITH_ZSTD = "ON")
`

**Comment by starsareintherose** [comment]
@sukanka Could I know where can I set this in pkgbuild

**Comment by hubutui** [comment]
According to [this](https://arrow.apache.org/docs/r/articles/install.html#advanced-configuration-for-building-from-source), `ARROW_WITH_ZSTD` is set to `ON` by default. I'm not sure why it did not work.

You could set env, just like this:

https://github.com/BioArchLinux/Packages/blob/e2ccdbef4dc9efccfaa526531072542bc77d4a56/BioArchLinux/r-av/PKGBUILD#L26-L29

**Comment by starsareintherose** [comment]
Do you mean like this
```
R CMD INSTALL  --configure-vars=“ARROW_WITH_ZSTD=ON”
```

**Comment by hubutui** [comment]
Yeah. Or you could prepend it to the command, like this:
```
ARROW_WITH_ZSTD=ON R CMD INSTALL ...
```
Or just export it before the install command.

**Comment by bshor** [comment]
Thank you! This fixed the issue.

**Comment by hubutui** [comment]
@starsareintherose Actually, `r-arrow` is the R binding for [arrow](https://archlinux.org/packages/community/x86_64/arrow/), we don't need to build arrow at all, just add `arrow` as deps of `r-arrow`. `ARROW_WITH_ZSTD` is enabled by default when ArchLinux maintainer building arrow, see https://github.com/archlinux/svntogit-community/blob/packages/arrow/trunk/PKGBUILD.

**Comment by hubutui** [comment]
@starsareintherose Since we use `arrow` from ArchLinux official repo, `--configure-vars="ARROW_WITH_ZSTD=ON"` is not used anymore.
https://github.com/BioArchLinux/Packages/blob/345ce53c9efd964a233436ed7fda77fda0f60b5e/BioArchLinux/r-arrow/PKGBUILD#L56

**Comment by starsareintherose** [comment]
Okay

**Comment by hubutui** [comment]
`libcurl-compat` and `openssl` are deps of `arrow` if S3 & GCS support are enabled. I don't think we need them as `r-arrow`'s deps.
