### ISSUE TITLE
[BUG] The ugene package does not install everything needed

### ISSUE THREAD

**Issue by staalmannen** [BioArchLinux/Packages#12]
OK this is annoying. I made the package based on my ugene-git package (which works) but apparently is the ugene package in BioArchLinux not installing everything (PREFIX has to be set on both "qmake" and "make install", but even that did not help). When upstream changed how things are supposed to be installed in ugene, it really messed up the package.

Sorry.
I will have to try to figure out what goes wrong in the release version of the package. I will do that sometime in the coming days.

**Comment by starsareintherose** [comment]
I think the problem may be caused by the server net, I see the log, now it's difficult to connect with the GitHub https repo to get it.

**Comment by staalmannen** [comment]
I have now verified that the package behaves differently depending on how you build it. I use aurutils and get different outcomes depending on how the package is built (exactly the same PKGBUILD file):

When I build ugene-git locally in my development folder with `aur build` , the package works and all the expected files are installed in the PREFIX.

When I build exactly the same package but using the AUR helper part of aurutils by running `aur sync ugene-git` I get the package with only some files installed in PREFIX. There is thus some sort of difference between how different files get installed in ugene and somehow some of them are sensitive to the build directory / packaging method.

**Comment by starsareintherose** [comment]
right, it's critical, but I think lilac use the devtools

**Comment by staalmannen** [comment]
The install problem is fixed upstream: ugeneunipro/ugene#683

**Comment by staalmannen** [comment]
So the package *should* work next version release

**Comment by hubutui** [comment]
It seems you forget to use `${pkgver}` in `source`:
https://github.com/BioArchLinux/Packages/blob/c9884fde2885a0907df351c9fda3fc4c92004e81/BioArchLinux/ugene/PKGBUILD#L18
It would not be automatically updated.

**Comment by starsareintherose** [comment]
fixed
