### ISSUE TITLE
[MAINTAIN] `bioarchlinux-keyring` has been _downgraded_. What is going on?, and increment `$epoch`.

### ISSUE THREAD

**Issue by dreirund** [BioArchLinux/Packages#129]
I see that the package `bioarchlinux-keyring` from the Arch Linux repository "[bioarchlinux](https://wiki.archlinux.org/title/Unofficial_user_repositories#bioarchlinux) has been _downgraded_ in your repository!:

```
Package (1)                        Old Version  New Version
bioarchlinux/bioarchlinux-keyring  20220422-2   2022.04.16-1
```

Can you please elaborate on that, what went wrong, and if you really need to replace with an older version, increment `$epoch` to ensure updates?

Regards!

**Packages (please complete the following information):**
 - Package Name: bioarchlinux-keyring

**Comment by starsareintherose** [comment]
Okay, sorry for that

**Comment by dreirund** [comment]
> *Okay, sorry for that*

And what was the reason for downgrade? Downgrading (revoking?) cryptography keys does always give rise to suspicion, so can you write a post-mortem, please?

**Comment by dreirund** [comment]
> *Okay, sorry for that*

And what was the reason for downgrade? Downgrading (revoking?) cryptography keys does always give rise to suspicion, so can you write a post-mortem, please?
