### ISSUE TITLE
[BUG] FastQC AUR build fails

### ISSUE THREAD

**Issue by mmahmoudian** [BioArchLinux/Packages#130]
This is regarding the [fastq AUR](https://aur.archlinux.org/packages/fastqc) which is based on the following file and is maintained by @starsareintherose :

https://github.com/BioArchLinux/Packages/blob/master/BioArchLinux/fastqc/PKGBUILD

While updating the fastQC AUR, I got the following error. I believe it is bevause the `javac -target` should be `1.8` instead of `11` which is [defined in the `build.xml`](https://github.com/s-andrews/FastQC/blob/d4f2e91d67b765867b59cde3c6a9a6c7de34ae37/build.xml#L10). The following is verbatim from the `man javac`:

> ```
>        -target version
>               Generates class files that target a specified release of the virtual machine. Class files will
>               run on the specified target and on later releases, but not on earlier releases of the JVM.
>               Valid targets are 1.1, 1.2, 1.3, 1.4, 1.5 (also 5), 1.6 (also 6), 1.7 (also 7), and 1.8 (also 8).
>               The default for the -target option depends on the value of the -source option:
>               
>               • If the -source option is not specified, then the value of the -target option is 1.8
>               • If the -source option is 1.2, then the value of the -target option is 1.4
>               • If the -source option is 1.3, then the value of the -target option is 1.4
>               • If the -source option is 1.5, then the value of the -target option is 1.8
>               • If the -source option is 1.6, then the value of the -target is option 1.8
>               • If the -source option is 1.7, then the value of the -target is option 1.8
>               • For all other values of the -source option, the value of the -target option is the value
>                 of the -source option.
> ```

This means we have to patch the `build.xml` during the AURs `prepare` function to replace the following lines to have the correct value:

https://github.com/s-andrews/FastQC/blob/d4f2e91d67b765867b59cde3c6a9a6c7de34ae37/build.xml#L10-L11

**Log of the bug**

<details><summary>My terminal output</summary>

```console
❯  paru
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
warning: r: ignoring package upgrade (4.0.3-2 => 4.2.3-1)
 there is nothing to do
:: Looking for AUR upgrades...
:: Looking for devel upgrades...
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (1) fastqc-0.12.1-2

:: Proceed to review? [Y/n]: y

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
 nothing new to review
fetching devel info...
==> Making package: fastqc 0.12.1-2 (Wed 26 Apr 2023 10:47:14 AM EEST)
==> Retrieving sources...
  -> Found fastqc-0.12.1
  -> Found fastqc.patch
==> Validating source files with md5sums...
    fastqc-0.12.1 ... Passed
    fastqc.patch ... Passed
==> Making package: fastqc 0.12.1-2 (Wed 26 Apr 2023 10:47:15 AM EEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found fastqc-0.12.1
  -> Found fastqc.patch
==> Validating source files with md5sums...
    fastqc-0.12.1 ... Passed
    fastqc.patch ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting fastqc-0.12.1 with bsdtar
==> Starting prepare()...
patching file build.xml
==> Sources are ready.
fastqc-0.12.1-2: parsing pkg list...
==> Making package: fastqc 0.12.1-2 (Wed 26 Apr 2023 10:47:16 AM EEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Removing existing $pkgdir/ directory...
==> Starting build()...
Buildfile: /home/mehrad/.cache/paru/clone/fastqc/src/FastQC-0.12.1/build.xml

build-subprojects:

init:
    [mkdir] Created dir: /home/mehrad/.cache/paru/clone/fastqc/src/FastQC-0.12.1/bin
     [copy] Copying 59 files to /home/mehrad/.cache/paru/clone/fastqc/src/FastQC-0.12.1/bin

build-project:
     [echo] FastQC: /home/mehrad/.cache/paru/clone/fastqc/src/FastQC-0.12.1/build.xml
    [javac] Compiling 138 source files to /home/mehrad/.cache/paru/clone/fastqc/src/FastQC-0.12.1/bin
    [javac] javac: invalid target release: 11
    [javac] Usage: javac <options> <source files>
    [javac] use -help for a list of possible options

BUILD FAILED
/home/mehrad/.cache/paru/clone/fastqc/src/FastQC-0.12.1/build.xml:36: Compile failed; see the compiler error output for details.

Total time: 0 seconds
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'fastqc-0.12.1-2':
error: packages failed to build: fastqc-0.12.1-2
```
 
 </details>

**Desktop (please complete the following information):**
 - Desktop Enviroment: KDE Plasma v5.27.4
 - Linux Kernel: 6.1.25-1-MANJARO
 - Package Version: [e.g. 22]

**Additional context**
--not applicable--

**Comment by kbipinkumar** [comment]
i am not the maintainer of the said package. that said, fastqc seems to have been successfully built by bioarchlinux's build server in a clean chroot as per the [log](https://build.bioarchlinux.org/api/pkg/fastqc/log/1682437849)

```
==> Starting build()...
Buildfile: /build/fastqc/src/FastQC-0.12.1/build.xml

build-subprojects:

init:
    [mkdir] Created dir: /build/fastqc/src/FastQC-0.12.1/bin
     [copy] Copying 59 files to /build/fastqc/src/FastQC-0.12.1/bin

build-project:
     [echo] FastQC: /build/fastqc/src/FastQC-0.12.1/build.xml
    [javac] Compiling 138 source files to /build/fastqc/src/FastQC-0.12.1/bin
    [javac] warning: [options] system modules path not set in conjunction with -source 11
    [javac] /build/fastqc/src/FastQC-0.12.1/org/apache/commons/math3/util/MathUtils.java:57: warning: [removal] Double(double) in Double has been deprecated and marked for removal
    [javac]         return new Double(value).hashCode();
    [javac]                ^
    [javac] /build/fastqc/src/FastQC-0.12.1/org/apache/commons/math3/util/ResizableDoubleArray.java:915: warning: [removal] Float(float) in Float has been deprecated and marked for removal
    [javac]         hashData[0] = new Float(expansionFactor).hashCode();
    [javac]                       ^
    [javac] /build/fastqc/src/FastQC-0.12.1/org/apache/commons/math3/util/ResizableDoubleArray.java:916: warning: [removal] Float(float) in Float has been deprecated and marked for removal
    [javac]         hashData[1] = new Float(contractionCriteria).hashCode();
    [javac]                       ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 4 warnings

build:

BUILD SUCCESSFUL

```
if i may make a suggestion why not add Bioarchlinux repo to your pacman and repository and install fastqc from there?

**Comment by starsareintherose** [comment]
I am a bit confused, because upstream is 11, should I specific the java-environment=11 and java-runtime=11, as it can be built under devtools, I don't know what's happening for this.

**Comment by starsareintherose** [comment]
It would a manjaro issue, I guess, I would suggest that you should go to arcolinux or endeavors or other arch-based distros syncing with upstream arch, it would be okay, I guess. Or try to switch 

Please report to manajaro forum also, let me track this issue.

**Comment by mmahmoudian** [comment]
Thanks for the responses. I tried the following on a clean-install VM of Arch to see if there is any issue. 

```sh
sudo pacman -S --needed base-devel
sudo pacman -S git
git clone https://aur.archlinux.org/fastqc.git
cd fastqc
makepkg -si
```

I tried with default jre dependency (`jre-openjdk`) and then what I have on my computer (`jre11-openjdk`). The following shows what I have on my computer and what is on Manjaro repo for now:

![image](https://user-images.githubusercontent.com/390889/234585998-6190e943-b201-4e92-adc7-8ecaa1cd8114.png)


Both built correctly. The following is with the jre I have on my machine:

[Peek 2023-04-26 16-04.webm](https://user-images.githubusercontent.com/390889/234584484-3f3906ad-8f09-4e15-9cf6-e120ca748cea.webm)

The only difference I see between my computer and this Arch VM (apart from the distro) is the version of `jre-openjdk`

**Comment by starsareintherose** [comment]
Yeah, this is manjaro issue. I limit the version in AUR, you can tried, if not, I would suggest switch to unstable branch to follow arch

**Comment by mmahmoudian** [comment]
> Again, when you report your issue to arch related distro or repo, please specific that you are manjaro user, it's special

I know it is different, and that was the reason I wrote it in the first post to be transparent and clear:

![image](https://github.com/BioArchLinux/Packages/assets/390889/4db49e38-2846-4f53-ba93-159f149e2823)

-------

> this is manjaro issue.

After some short [discussion on Manjaro forum](https://forum.manjaro.org/t/getting-javac-javac-invalid-target-release-11-inspite-of-having-jre11-openjdk/142783), it got clear that this is not Manjaro issue, but bad installer and instruction issue which *can affect Arch and all it's derivatives*. 

The [Arch wiki about Java](https://wiki.archlinux.org/title/Java) reads:

> > Arch Linux officially supports the open source [OpenJDK](https://openjdk.java.net/) versions 8, 11, 17 and 20. All these JVM can be installed without conflict and switched between using helper script `archlinux-java`

So in the PKGBUILD you should add a part to check if the suitable java is the default (e.g using `archlinux-java get` or `archlinux-java status`) and prompt the user to install/activate the version you would need. Alternatively, the build system should be able to temporarily switch things for the build to get completed and then revert the version to whatever user has set.

In summary and conclusion, Arch allows installation of multiple OpenJDK side-by-side and if the AUR needs a particular version, it should be able to:
1. inform user
2. adjust the versions and environment if the required OpenJDK is already installed

--------

For others ending up here, until the AUR is fixed to handle the issue, follow these steps:

1. check what JDKs you have installed:
    ```sh
    archlinux-java status
    ```
    The output should be something like:
    > ```
    >   Available Java environments:
    >     java-11-openjdk
    >     java-8-openjdk (default)
    > ```
2. if you don't have `java-11-openjdk` installed, install it first:
    ```sh
    sudo pacman -S jdk11-openjdk
    ```
3. change the version using `archlinux-java`:
    ```sh
    sudo archlinux-java set java-11-openjdk
    ```

**Comment by starsareintherose** [comment]
...

**Comment by mmahmoudian** [comment]
@starsareintherose 

Thanks for the quick response, but For some reason your message only appears as ellipsis at my end. Please let me know if there is anything else that I can help with, or if you need some further information.

Cheers.

**Comment by starsareintherose** [comment]
If you don't know how to get information from archwiki, you shouldn't use archlinux or archlinux based distributions but manjaro.

Even I don't want to say the truth, but I have to say it again, sadlly, this issue is due to different timetable between manjaro and archlinux, so, actually it's manjaro's java version issue, you even shouldn't complain it at any other distro

**Comment by starsareintherose** [comment]
The only standard is that it can be compiled successful under devtools of archlinux

**Comment by Kiri2002** [comment]
> Thanks for the responses. I tried the following on a clean-install VM of Arch to see if there is any issue.
> 
> ```shell
> sudo pacman -S --needed base-devel
> sudo pacman -S git
> git clone https://aur.archlinux.org/fastqc.git
> cd fastqc
> makepkg -si
> ```
> 
> I tried with default jre dependency (`jre-openjdk`) and then what I have on my computer (`jre11-openjdk`). The following shows what I have on my computer and what is on Manjaro repo for now:
> 
> ![image](https://user-images.githubusercontent.com/390889/234585998-6190e943-b201-4e92-adc7-8ecaa1cd8114.png)
> 
> Both built correctly. The following is with the jre I have on my machine:
> Peek.2023-04-26.16-04.webm
> 
> The only difference I see between my computer and this Arch VM (apart from the distro) is the version of `jre-openjdk`

hey, what's your machine  is, looks very cool, a touchpad ?

**Comment by mmahmoudian** [comment]
🤦🏼 This is for you to **learn** that in Arch multiple java version is available:

https://archlinux.org/packages/?q=jdk

Read my comments enough times until you understand your mistakes.  I rest my case.

**Comment by starsareintherose** [comment]
To be honest, this issue shouldn't exist, when you propose it, you actually bother me, I am impolite enough, if you want to earn my respect, go away from Manjaro!

This is not my turn to learn Arch, it's your turn to understand why Manjaro is different from Arch and why you meet this issue. Don't show me how many version, just remember how to `archlinux-java`, if you think it's a problem, report to every Arch Java pkgs, plz!

**Comment by starsareintherose** [comment]
Again, go to understand devtools, plz
