### ISSUE TITLE
[BUG] r-v8 AUR PKGBUILD overwrites its own source archive

### ISSUE THREAD

**Issue by pekkarr** [BioArchLinux/Packages#131]
The `prepare` function in r-v8 `PKGBUILD` [overwrites the source tarball](../blob/4aa84447d16cf77edd104c7616d31ded64e6c750/BioArchLinux/r-v8/PKGBUILD#L34), which causes all rebuild attempts after that to fail because the sha256sum won't match the archive anymore. Also some AUR helpers (paru in chroot mode) run `prepare` and `build` in separate `makepkg` invocations which means that the sha256sum won't match on the second `makepkg`.

`R CMD INSTALL` can install directly from the extracted and patched directory, so there's no need to compress it again. This patch would fix the `PKGBUILD`:

```patch
diff --git a/PKGBUILD b/PKGBUILD
index ec8d581..fb67370 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -31,16 +31,16 @@ prepare() {
   # build with system nodejs
   sed -i '11,12d' ${_pkgname}/configure
   sed -i '11i PKG_LIBS="-lnode"\nPKG_CFLAGS="-I/usr/include/node"' ${_pkgname}/configure
-  tar cvfz ${_pkgname}_${pkgver}.tar.gz ${_pkgname}
 }
 
 build() {
-  R CMD INSTALL ${_pkgname}_${pkgver}.tar.gz -l "${srcdir}"
+  mkdir -p build
+  R CMD INSTALL ${_pkgname} -l build
 }
 
 package() {
   install -dm0755 "${pkgdir}/usr/lib/R/library"
-  cp -a --no-preserve=ownership "${_pkgname}" "${pkgdir}/usr/lib/R/library"
+  cp -a --no-preserve=ownership "build/${_pkgname}" "${pkgdir}/usr/lib/R/library"
   install -Dm644 "${_pkgname}/LICENSE" -t "${pkgdir}/usr/share/licenses/${pkgname}"
 }
 # vim:set ts=2 sw=2 et:
```

**Desktop (please complete the following information):**
 - Package Version: `r-v8 4.3.0-1`

**Comment by starsareintherose** [comment]
Yeah, thanks, do you want to pr

**Comment by pekkarr** [comment]
Thanks for quickly fixing it!
