### ISSUE TITLE
[MAINTAIN] r-v8 requires a rebuild due to nodejs update

### ISSUE THREAD

**Issue by pekkarr** [BioArchLinux/Packages#135]
Nodejs in the [official Arch repo](https://archlinux.org/packages/community/x86_64/nodejs/) was updated to version 20.2.0, which includes a version bump to the `libnode.so` shared library that `r-v8` depends on. Rebuilding `r-v8` is required for linking with the new soname.

`r-v8` is source compatible with the new nodejs, so a `pkgrel` bump is enough for the rebuild.

**Packages**
 - `r-v8` 4.3.0-3

**Comment by starsareintherose** [comment]
Thanks for reporting it, Could you check this pkgrel a84f767199e78e70ac001475bb5730e659273b79

**Comment by pekkarr** [comment]
Yeah the built 4.3.0-4 package looks fine. Could you push this to AUR as well?

**Comment by starsareintherose** [comment]
I'm sorry as usually, lilac won't bump pkgrel for AUR for this situation, I will manually do it.

**Comment by starsareintherose** [comment]
now I updated

**Comment by starsareintherose** [comment]
Yeah I see, quite a lot of R pkgs, you can maintain them via our bot.

1. I think it's okay to give patch, as quite a lot of pkgs need patch to be built.
2. I don't care about `check`, sometimes we mv them as we can't build pkgs with checking.

So you can decide

**Comment by pekkarr** [comment]
Thanks, I'll make myself familiar with the bot first.

This seems like a cool project. I'll happily contribute to it.

**Comment by starsareintherose** [comment]
Okay, check your email, I've invited. You can join our tg or matrix group for future communication

**Comment by pekkarr** [comment]
The invitation is now accepted. I also joined the matrix group.
