### ISSUE TITLE
[REQUEST] Add FIJI

### ISSUE THREAD

**Issue by I-Love-BioArchLinux** [BioArchLinux/Packages#160]
**Information**
 - Package Name: FIJI
 - Can it directly run on Linux: yes
 - Can it run on the wine: N/A
 -  Website: https://fiji.sc
 - Download URL: https://downloads.imagej.net/fiji/latest/fiji-linux64.zip
 - Package description: ImageJ distribution with a lot of plugins for scientific (especially biology related) image processing.
 - DOI: https://doi.org/10.1038/nmeth.2019
 

**Popularity**
 - Number of citations in google scholar: 23647 in last three years [2020,2022]
 - Any other reason: if you use optical microscope, you must use FIJI (FIJI is just ImageJ)

**Comment by starsareintherose** [comment]
Spam from @Kiri2002
