### ISSUE TITLE
[REQUEST] Add CellProfiler

### ISSUE THREAD

**Issue by I-Love-BioArchLinux** [BioArchLinux/Packages#161]
**Information**
 - Package Name: CellProfiler
 - Can it directly run on Linux: N/A
 - Can it run on the wine: N/A
 -  Website: https://cellprofiler.org
 - Download URL: https://cellprofiler.org/releases
 - Package description: Software for quantitative analysis of biological images
 - DOI: https://doi.org/10.1371/journal.pbio.2005970
 

**Popularity**
 - Number of citations in google scholar: 1220  in last three years [2020,2022]
 - Any other reason: if you study Cell Biology, you must use CellProfiler

**Comment by starsareintherose** [comment]
Spam from @Kiri2002
