### ISSUE TITLE
[REQUEST] Add QIIME2

### ISSUE THREAD

**Issue by I-Love-BioArchLinux** [BioArchLinux/Packages#163]
**Information**
 - Package Name: qiime2
 - Can it directly run on Linux: yes
 - Can it run on the wine: not
 -  Website: https://qiime2.org
 - Download URL:   (GUI version, q2galaxy : https://github.com/qiime2/q2galaxy/releases/tag/2023.5.0) (CLI version, q2cli : https://github.com/qiime2/q2cli/releases/tag/2023.5.1)
 - Package description:  QIIME 2 is a next-generation microbiome bioinformatics platform that is extensible, free, open source, and [community developed.](https://github.com/orgs/qiime2/people)
 - DOI: https://doi.org/10.1038/s41587-019-0209-9
 

**Popularity**
 - Number of citations : 7218 Citations since 2019
 - Any other reason: microbiome bioinformatics  must use it !!!

**Comment by starsareintherose** [comment]
Spam from @Kiri2002
