### ISSUE TITLE
[REQUEST] Add copasi

### ISSUE THREAD

**Issue by I-Love-BioArchLinux** [BioArchLinux/Packages#169]
**Information**
 - Package Name: copasi
 - Can it directly run on Linux: yes
 -  Website: https://copasi.org 
                    or https://github.com/copasi/COPASI
 - Download URL: https://copasi.org/Download
                                or https://github.com/copasi/COPASI/releases
 - Package description:  COmplex PAthway SImulator for analysis of biochemical networks and their dynamics
 - DOI: https://doi.org/10.1093/bioinformatics/btl485
 

**Popularity**
 - Number of three years citations from googel scholar: 851 [2019-2023]
 - Any other reason: Important for enzyme design expecially for _in vitro_ multi-enzyme molecular machines

![image](https://github.com/BioArchLinux/Packages/assets/90973207/96f4f126-bece-4bd9-8e2a-debf6be35273)

PS:
found two built bin version in aur:
https://aur.archlinux.org/packages/copasi
https://aur.archlinux.org/packages/copasi-bin

**Comment by starsareintherose** [comment]
Spam from @Kiri2002
