### ISSUE TITLE
[REQUEST] Add vcell

### ISSUE THREAD

**Issue by I-Love-BioArchLinux** [BioArchLinux/Packages#170]
**Information**
 - Package Name: vcell
 - Can it directly run on Linux: yes
 -  Website: https://vcell.org/
 - Github: https://github.com/virtualcell/vcell
 - Download URL: https://vcell.org/run-vcell-software
 - Package description: A comprehensive platform for modeling cell biological systems.
 - DOI: 10.1016/j.bpj.2017.08.022 
 
![image](https://github.com/BioArchLinux/Packages/assets/90973207/fa8a8e35-52c6-49de-8821-b837e84e6d63)

**Comment by starsareintherose** [comment]
Spam from @Kiri2002
