### ISSUE TITLE
[REQUEST] Add SpringSaLaD

### ISSUE THREAD

**Issue by I-Love-BioArchLinux** [BioArchLinux/Packages#171]
**Information**
 - Package Name: springsalad
 - Can it directly run on Linux: yes
 -  Website: https://vcell.org/ssalad
 - Download URL: https://vcell.org/ssalad
 - Github: https://github.com/cam-center/SpringSaLaD
 - Package description:  a particle-based, stochastic, biochemical simulation platform most suitable for modeling mesoscopic systems
 - DOI: 10.1016/j.bpj.2015.12.026 
 
![image](https://github.com/BioArchLinux/Packages/assets/90973207/005d4317-63ce-4a4e-b2dc-f953dcc6c67c)

**Comment by starsareintherose** [comment]
Spam from @Kiri2002
