### ISSUE TITLE
[REQUEST] Add MEME Suit tools

### ISSUE THREAD

**Issue by Kiri2002** [BioArchLinux/Packages#185]
**Information**
 - Package Name: meme
 - Can it directly run on Linux: yes
 -  Website: https://meme-suite.org/meme
 - Download URL: https://meme-suite.org/meme/doc/download.html
 - Package description: Motif-based sequence analysis tools. 
 - DOI: https://doi.org/10.1093/nar/gkv416
 

**Popularity**
 - Number of citations from google scholar 2019-2023: ~16,900
 
![image](https://github.com/BioArchLinux/Packages/assets/125180256/e3e0d626-50a6-4fff-9854-8f0d41609e6b)

**Comment by Kiri2002** [comment]
Sorry to bother here. Lack of C knowledge, I can't fix the "err log" in the file(meme-5.5.3-1-x86_64.pkg.tar.zst-namcap.log).
I couldn't appreciate more that someone smart and kind to solve this.
Here are PKGBUILD , liliac.yaml(removed my name and mail) and logs.
Thank you.
  
[PKGBUILD.txt](https://github.com/BioArchLinux/Packages/files/12387126/PKGBUILD.txt)
[lilac.yaml.txt](https://github.com/BioArchLinux/Packages/files/12387127/lilac.yaml.txt)
[meme-5.5.3-1-x86_64.pkg.tar.zst-namcap.log](https://github.com/BioArchLinux/Packages/files/12387128/meme-5.5.3-1-x86_64.pkg.tar.zst-namcap.log)
[meme-5.5.3-1-x86_64-package.log](https://github.com/BioArchLinux/Packages/files/12387129/meme-5.5.3-1-x86_64-package.log)
[meme-5.5.3-1-x86_64-build.log](https://github.com/BioArchLinux/Packages/files/12387131/meme-5.5.3-1-x86_64-build.log)

**Comment by starsareintherose** [comment]
There are two ways to solve it.

- Firstly, sed build-related files to replace libexec with lib or whatever
- The second methods is after installed mv directory manually


Now you can have a try

**Comment by starsareintherose** [comment]
Spam from @Kiri2002

**Comment by Kiri2002** [comment]
How spam? Where break rule? And why don't close at 2 weeks ago in your first reply?

Not spam, but excuse.

LMFAO

**Comment by Kiri2002** [comment]
Why not just remove the tag of 'feature', if you don't accept NEW pkg

**Comment by starsareintherose** [comment]
I couldn't help you at the beginning if I knew you are an impolite and annoying person who always asked vampire questions

**Comment by Kiri2002** [comment]
> I couldn't help you at the beginning if I knew you are an impolite and annoying person who always asked vampire questions

So this is the real close reason,
> because issues from Kiri who is impolite, annoying and always asked vampire questions.
Not spam.
This mean, when one u think one bad, the one's issue bad too.
LOL
