### ISSUE TITLE
r-arrow should be rebuilt or upgraded

### ISSUE THREAD

**Issue by LC0117** [BioArchLinux/Packages#187]
**Log of the bug**

<details>

```
Error: package or namespace load failed for 'arrow' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/lib/R/library/arrow/libs/arrow.so':
  libarrow.so.1000: cannot open shared object file: No such file or directory

```
 
 </details>

**Desktop (please complete the following information):**
 - Desktop Enviroment: kde
 - Linux Kernel: linux-zen, 6.4.12
 - Package Version: 10.0.0-5

**Additional context**

**Comment by starsareintherose** [comment]
fixed 945aa4a6b4218d1bc62fd6ebdbdf4f6ab037b391
