### ISSUE TITLE
[MAINTAIN] IRA: /startdir/PKGBUILD: line 17: cd: LRA-V1.10: No such file or directory

### ISSUE THREAD

**Issue by starsareintherose** [BioArchLinux/Packages#19]
**Log of the bug**

<details>

```
[1m[34m  ->(B[m[1m Extracting V1.10.tar.gz with bsdtar(B[m
[1m[32m==>(B[m[1m Starting build()...(B[m
/startdir/PKGBUILD: line 17: cd: LRA-V1.10: No such file or directory
[1m[31m==> ERROR:(B[m[1m A failure occurred in build().(B[m
```
 
 </details>

**Packages (please complete the following information):**
 - Package Name: [e.g. iqtree]

**Description**

**Comment by michaelgelliot** [comment]
Hi, is this in package lra? I cannot replicate the error, the pkgver is not 1.10
![image](https://user-images.githubusercontent.com/96027805/148154911-3dd2ca0e-ae08-4452-908b-4b88f87c8c52.png)

**Comment by starsareintherose** [comment]
okay, I got it, you can see https://github.com/ChaissonLab/LRA/tags v1.10 is larger than the latest tag

**Comment by michaelgelliot** [comment]
Ah, OK! I understand. I think I will have to take some time to properly understand lilac.... Sorry about this.

**Comment by starsareintherose** [comment]
I changed it and see the lilac.yaml,  you can find I add the depends on hstlib, it's not in the extra or x86 official repo of ArchLinux but in ours, so you should add what I added, you are great in lilac.yaml now I think.

**Comment by michaelgelliot** [comment]
I will take a look at what you did, tomorrow. Thanks! I'll get better...._
