### ISSUE TITLE
[MAINTAIN] Delete obsolete R packages

### ISSUE THREAD

**Issue by pekkarr** [BioArchLinux/Packages#197]
These packages have been removed from CRAN or Bioconductor and are not depended on by any package in this repo or in AUR.

- r-aspediafi
- r-copywriter
- r-epihet
- r-genotypeeval
- r-metavizr
- r-optimr
- r-perturbatr (already archived in the repo but deleting this allows us to get rid of r-diffusr)
- r-profia
- r-stan
- r-tarseqqc
- r-uchardet

@starsareintherose Could you send AUR deletion requests for these packages using the BioArchLinuxBot account? I can take care of deleting the packages from the repo.

After the previous list has been deleted from AUR, we can submit deletion requests for the following package list. These have been removed from CRAN, but are still depended on by packages from the previous list.

- r-diffusr (requires deleting r-perturbatr first)
- r-rcgmin (requires deleting r-optimr first)
- r-rvmmin (requires deleting r-optimr first)

**Comment by pekkarr** [comment]
Thank you, I deleted the packages from the repo as well.

**Comment by starsareintherose** [comment]
All done

**Comment by pekkarr** [comment]
Great, now they are deleted in the repo too.
