### ISSUE TITLE
[MAINTAIN] Delete obsolete R packages 2

### ISSUE THREAD

**Issue by pekkarr** [BioArchLinux/Packages#205]
These packages have been removed from CRAN or Bioconductor and are not depended on by any package in this repo or in the AUR.

I have divided them into batches in such a way that AUR deletion requests for **batch 1** need to be accepted before submitting requests for **batch 2** etc. because packages in **batch 1** depend on **batch 2** packages.

### Batch 1

- r-assertive
- r-isogenegui
- r-sparsebn

### Batch 2

- r-assertive.matrices
- r-assertive.models
- r-assertive.reflection
- r-ccdralgorithm
- r-discretecdalgorithm
- r-isogene

### Batch 3

- r-sparsebnutils

@starsareintherose Can you submit AUR deletion requests for **batch 1** using the BioArchLinuxBot account?

**Comment by starsareintherose** [comment]
Done for batch1

**Comment by starsareintherose** [comment]
Done for bartch2

**Comment by starsareintherose** [comment]
Done for batch3
