### ISSUE TITLE
[BUG] imagej2 package from repo not launching. 

### ISSUE THREAD

**Issue by kbipinkumar** [BioArchLinux/Packages#219]
The application does not start. when i tried to launch the application from terminal `/usr/bin/imagej2`i got the following output

**Log of the bug**
#<details>
```
$ /usr/bin/imagej2
Error, no compatiable java found! imagej2 depends on java 8
```
 
 </details>

**Desktop (please complete the following information):**
 - Desktop Enviroment: KDE
 - Linux Kernel: 6.10.6-zen1-1-zen
 - Package Version: 2.15.0-2 

**Additional context**

i have all the dependencies including jre8 installed as suggested by the package via pacman 

```shell
$ pacman -S imagej2 
resolving dependencies...
looking for conflicting packages...

Packages (4) java-runtime-common-3-5  jre8-openjdk-8.422.u05-1  jre8-openjdk-headless-8.422.u05-1  imagej2-2.15.0-2

$ pacman -Ss jre8
extra/jre8-openjdk 8.422.u05-1 [installed]
    OpenJDK Java 8 full runtime environment
extra/jre8-openjdk-headless 8.422.u05-1 [installed]
    OpenJDK Java 8 headless runtime environment

$ archlinux-java status
Available Java environments:
  java-8-openjdk/jre (default)
```

**Comment by starsareintherose** [comment]
How about `sudo archlinux-java set java-8-openjdk`

**Comment by kbipinkumar** [comment]
> sudo archlinux-java set java-8-openjdk

does not work.
```
sudo archlinux-java set java-8-openjdk
'/usr/lib/jvm/java-8-openjdk' is not a valid Java environment path
```

**Comment by starsareintherose** [comment]
```
local/jre17-openjdk 17.0.12.u7-1
    OpenJDK Java 17 full runtime environment
local/jre8-openjdk 8.422.u05-1
    OpenJDK Java 8 full runtime environment
local/jre8-openjdk-headless 8.422.u05-1
    OpenJDK Java 8 headless runtime environment
```
Have you installed

**Comment by kbipinkumar** [comment]
![Screenshot_20240829-121207.png](https://github.com/user-attachments/assets/e2d730e5-2493-4592-89ae-dd0c0a8afe66)

I have only the java dependencies installed by imageJ package itself. 

Ideally the binary should launch with dependencies that is packaged with package.

**Comment by starsareintherose** [comment]
> > sudo archlinux-java set java-8-openjdk
> 
> does not work.
> 
> ```
> sudo archlinux-java set java-8-openjdk
> '/usr/lib/jvm/java-8-openjdk' is not a valid Java environment path
> ```

It would be a bit strange, the reason is that archlinux-java is the pkg control the java environment, maybe try `sudo archlinux-java fix ` and `sudo archlinux-java status`

**Comment by pekkarr** [comment]
The issue is here:

https://github.com/BioArchLinux/Packages/blob/ba67bc902aeddc3026264c53c305173173413bb6/BioArchLinux/imagej2/PKGBUILD#L47-L48

The path there is wrong, it should be `/usr/lib/jvm/java-8-openjdk/jre/bin`.

Another bug is that the build time `${PATH}` is hardcoded into the script. It should use the runtime `${PATH}` instead by escaping the variable with a backslash `\${PATH}`
