### ISSUE TITLE
[MAINTAIN] bioconductor series

### ISSUE THREAD

**Issue by starsareintherose** [BioArchLinux/Packages#22]
<details>

- [x] r-crossmeta
- [x] r-mfa
- [x] r-srgnet
- [x] r-drugvsdisease
- [x] r-generegionscan
- [ ] r-puma
- [x] r-italics
- [x] r-prolocgui
- [x] r-nadfinder
- [x] r-frma
- [x] r-qqconf
- [x] r-mmuphin
- [x] r-travel
- [x] r-rqt
- [x] r-musicatk
- [x] r-affxparser
- [x] r-deconstructsigs
- [x] r-mimager
- [x] r-singlecelltk
- [x] r-affypara
- [x] r-oligo
- [x] r-pdinfobuilder
- [x] r-cn.farms
- [x] r-gramm4r
- [x] r-gcsscore
- [x] r-dmwr
- [x] r-affyilm
- [x] r-arrayexpresshts
- [x] r-kebabs
- [x] r-scan.upc
- [x] r-chipxpress
- [x] r-arrayexpress
- [x] r-lpsymphony
- [x] r-alps
- [x] r-metap
- [x] r-rgin
- [x] r-pd.mapping50k.xba240
- [x] r-proloc
- [ ] r-interactivedisplay
- [x] r-ideal
- [x] r-ccfindr
- [x] r-bibitr
- [x] r-encodeexplorer
- [x] r-eventpointer
- [x] r-ihw
- [x] r-synapter
- [x] r-swimr
- [x] r-sampling
- [x] r-maaslin2
- [x] r-mirsm
- [x] r-gfa
- [x] r-cancer
<details>

**Log of the bug**

<details>

```
put the output here
```
 
 </details>

**Packages (please complete the following information):**
 - Package Name: [e.g. iqtree]

**Description**

**Comment by hubutui** [comment]
If the installation hang at `** byte-compile and prepare package for lazy loading`, it's likely an upstream bug. You could try installing it in a clean R env with `BiocManager::install("pkgname")` to check it this method works.

**Comment by hubutui** [comment]
Check also this [repo](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/bioconductor-cancer), which holds the recipes to build packages available in [anaconda](https://anaconda.org/bioconda).

**Comment by starsareintherose** [comment]
transfered them into individual issues
