### ISSUE TITLE
[BUG] r-vscdebugger: Package links to outdated version 0.4.7 (from 2021!) while declaring itself as 0.5.3

### ISSUE THREAD

**Issue by major-mayer** [BioArchLinux/Packages#223]
From some reason, the package r-vscdebugger in this repository and on the AUR still links to version 0.4.7 from 2021:
https://aur.archlinux.org/packages/r-vscdebugger 
This links to the following URL in the sources:
 https://github.com/ManuelHentschel/vscDebugger/releases/download/v0.4.7/vscDebugger_0.4.7.tar.gz 

The most recent version is this one here: https://github.com/ManuelHentschel/vscDebugger/releases/tag/v0.5.3

It would be very nice if someone could update the sources, because as of now this package doesn't work with the corresponding VSCode extension.

**Desktop (please complete the following information):**
 - Desktop Enviroment: [e.g. gnome, kde, server] KDE
 - Linux Kernel: [e.g. linux-lts 5.10.60-1] Irrelevant 
 - Package Version: [e.g. 22] 0.4.7

**Additional context**

**Comment by sukanka** [comment]
Sorry, I'm on vacation now. I will look into this  Wednesday next week.

**Comment by major-mayer** [comment]
No worries, it's not urgent.
I just installed it manually in the meanwhile.
Enjoy your holidays

**Comment by starsareintherose** [comment]
I actually corrected that in PKGBUILD https://github.com/BioArchLinux/Packages/commit/94f59ea5cfcccf16ceec76ba648c402f995eaf11 , I need to let it rebuild when I have time to access server

**Comment by major-mayer** [comment]
Great thanks for your quick fix

**Comment by starsareintherose** [comment]
fixed f9b0b337f9b7ea5c2fd297fda616d57c38180cb5

You may need mirror to sync

**Comment by major-mayer** [comment]
It's a bit unfortunate that users don't get the new package update automatically, without manually re-installing it, but I guess you can't do much about it from your side, right...?
