### ISSUE TITLE
[BUG] `lilac_r_utils` requires `pkgdesc` to be in short format.

### ISSUE THREAD

**Issue by sukanka** [BioArchLinux/Packages#237]
**Log of the bug**

`r-dfoptim` failed to be built for `pkgdesc` mismatch, see the [log](https://build.bioarchlinux.org/api/pkg/r-dfoptim/log/1734750739)

According to its [main page](https://cran.r-project.org/web/packages/dfoptim/index.html)

```
dfoptim: Derivative-Free Optimization
Derivative-Free optimization algorithms. These algorithms do not require gradient information. More importantly, they can be used to solve non-smooth optimization problems.
```
 
`Derivative-Free Optimization` is a short description, and the following line is a detailed one. 

I think both are OK in `PKGBUILD`, but only the short one is allowed in `lilac_r_utils`

**Comment by pekkarr** [comment]
According to [Arch wiki](https://wiki.archlinux.org/title/PKGBUILD#pkgdesc), the `pkgdesc` field is recommended to be at most 80 characters long. The short description field is more likely to fit into that, so I think we should keep using it.

Currently the description is parsed from the `Title` field in the R package `DESCRIPTION` file, while the longer description would be in the `Description` field.

It is possible to override the `pkgdesc` checking by using the `expect_title` option to `r_pre_build`. For example:

```python
def pre_build():
    r_pre_build(
        _G,
        expect_title = "Derivative-Free Optimization",
    )
```

It will then check that the short description matches the provided one, and you can use anything in the `pkgdesc` field. See for example [r-tximportdata lilac.py](../blob/master/BioArchLinux/r-tximportdata/lilac.py).

In the case of `r-dfoptim` however, I think using the short description as `pkgdesc` is the correct choice.

**Comment by sukanka** [comment]
OKay, I will change its `pkgdesc`, thanks for your comment.
