### ISSUE TITLE
[MAINTAIN] r-interactivedisplay

### ISSUE THREAD

**Issue by starsareintherose** [BioArchLinux/Packages#36]
**Log of the bug**

<details>

```
* installing *source* package ‘interactiveDisplay’ ...
** using staged installation
** R
** data
** inst
** byte-compile and prepare package for lazy loading
Installing package into ‘/build/r-interactivedisplay/src/00LOCK-interactiveDisplay/00new’
(as ‘lib’ is unspecified)
Error in contrib.url(repos, type) : 
  trying to use CRAN without setting a mirror
Error: unable to load R code in package ‘interactiveDisplay’
Execution halted
ERROR: lazy loading failed for package ‘interactiveDisplay’
* removing ‘/build/r-interactivedisplay/src/interactiveDisplay’
* restoring previous ‘/build/r-interactivedisplay/src/interactiveDisplay’
==> ERROR: A failure occurred in build().
    Aborting...

```
 
 </details>

**Packages (please complete the following information):**
 - Package Name: [e.g. iqtree]

**Description**
https://log.bioarchlinux.org/2022-01-29T15%3A51%3A16/r-interactivedisplay.log

**Comment by hubutui** [comment]
This pkg could be build with `makepkg`, but not `BioArchLinux-x86_64-build`. But I just don't know why.

**Comment by starsareintherose** [comment]
@dvdesolve how can we deal with the mirror issue in PKGBUILD?

**Comment by dvdesolve** [comment]
may be it's a problem with mirror URL recognition when running under `BioArchLinux-x86_64-build`?

**Comment by starsareintherose** [comment]
now run under extrax-x86_64

**Comment by hubutui** [comment]
According to the error log, we need to set a default CRAN mirror. We could set it in file `.Rprofile`,  and set environment variable `R_PROFILE`.
quick fix:
```bash
prepare() {
  echo 'options(repos = list(CRAN = "http://cran.r-project.org"))' > "${srcdir}/.Rprofile"
}

build() {
  R_PROFILE="${srcdir}/.Rprofile" \
  R CMD INSTALL ${_pkgname}_${_pkgver}.tar.gz -l "${srcdir}"
}
```
