### ISSUE TITLE
[MAINTAIN] bioconductor upgrade issue: can't open shared lib

### ISSUE THREAD

**Issue by starsareintherose** [BioArchLinux/Packages#40]
**Log of the bug**
- [x] r-mzr: unable to load shared object '/build/r-mzr/src/00LOCK-mzR/00new/mzR/libs/mzR.so'
- [x] r-rsamtools: unable to load shared object '/build/r-rsamtools/src/00LOCK-Rsamtools/00new/Rsamtools/libs/Rsamtools.so'
- [x] r-rhdf5: unable to load shared object '/build/r-rhdf5/src/00LOCK-rhdf5/00new/rhdf5/libs/rhdf5.so'
- [x] r-bamsignals: unable to load shared object '/build/r-bamsignals/src/00LOCK-bamsignals/00new/bamsignals/libs/bamsignals.so'
- [x] r-flowcore: unable to load shared object '/build/r-flowcore/src/00LOCK-flowCore/00new/flowCore/libs/flowCore.so':
<details>

```
Error: package or namespace load failed for ‘Rsamtools’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/build/r-rsamtools/src/00LOCK-Rsamtools/00new/Rsamtools/libs/Rsamtools.so':
  /build/r-rsamtools/src/00LOCK-Rsamtools/00new/Rsamtools/libs/Rsamtools.so: undefined symbol: hts_open_format
Error: loading failed
Execution halted
ERROR: loading failed

```
 
 </details>

**Packages (please complete the following information):**
 - Package Name: [e.g. iqtree]

**Description**

**Comment by hubutui** [comment]
you could build it with `--no-test-load`, but still need to make sure it works as expected.
you could use `c++filt` to find out what the symbols mean, this might helps.

**Comment by starsareintherose** [comment]
if I add `--no-test-load` the packages depending on it always can't load the lib.

**Comment by hubutui** [comment]
Maybe it's a bug from upstream?

**Comment by starsareintherose** [comment]
> Maybe it's a bug from upstream?

they don't think so emmm

**Comment by christophfink** [comment]
It seems to be connected with Arch using LTO for building R, when I rebuilt R with `options=(!lto)`, things work fine. 

(compare https://github.com/Bioconductor/Rsamtools/issues/36#issuecomment-1114244878_ )

I filed a bug against the Arch package for R: https://bugs.archlinux.org/task/74609

**Comment by starsareintherose** [comment]
Though compiled with new version R, they all failed for the same reason, see https://log.bioarchlinux.org/2022-05-02T19%3A32%3A05/

**Comment by christophfink** [comment]
It works for r-rhtslib and r-rsamtools. Note that I added options=(!lto) to them, too.

**Comment by antonio-rojas** [comment]
Note that adding options=(!lto) to r-* packages is pointless, as they take the build flags form the R package and not from the system CFLAGS.

**Comment by christophfink** [comment]
@antonio-rojas : good to know, thanks! As a matter of fact, I had added `!buildflags` to the r-rsamtools PKGBUILD. Does that have any effect?

**Comment by starsareintherose** [comment]
Right, I also want to know, based on @christophfink I fixed the rsamtools related but others show similar issue about
```
 unable to load shared object '/build/r-flowcore/src/00LOCK-flowCore/00new/flowCore/libs/flowCore.so':
  /build/r-flowcore/src/00LOCK-flowCore/00new/flowCore/libs/flowCore.so: undefined symbol: _ZN7cytolib10in_polygonEPdS0_RKSt6vectorINS_10CYTO_POINTESaIS2_EERS1_IjSaIjEEbS9_
Error: loading failed
Execution halted
ERROR: loading fail
```

**Comment by antonio-rojas** [comment]
> Right, I also want to know, based on @christophfink I fixed the rsamtools related but others show similar issue about

You need to rebuild every package that ships static libraries (such as cytolib) with r 4.2.0-2

**Comment by dvdesolve** [comment]
rebuild of `r-rhdf5lib` with `staticlibs` option doesn't help for `r-mzr` package

**Comment by starsareintherose** [comment]
> rebuild of `r-rhdf5lib` with `staticlibs` option doesn't help for `r-mzr` package

I think I have rebuild all the depends they needed. So what should I do?

**Comment by dvdesolve** [comment]
if these packages now provide static libs that are used during linking step by the packages from the list in the first post, then all missing symbols now should be accessible. rebuild against updated packages should work fine

**Comment by starsareintherose** [comment]
but it seems I rebuild all depends, that's quite strange.

**Comment by dvdesolve** [comment]
@antonio-rojas could you help us please? Seems like rebuilding of all required packages with `staticlibs` against new R (4.2.0-2) doesn't help to fix issues

**Comment by antonio-rojas** [comment]
Please post the actual errors you're getting

**Comment by starsareintherose** [comment]
> Please post the actual errors you're getting

Thanks for your help

the log of mzr and flowcore is attached and the main issue is the mzr

[mzr.log](https://github.com/BioArchLinux/Packages/files/8654985/mzr.log)
[flowcore.log](https://github.com/BioArchLinux/Packages/files/8654984/flowcore.log)

**Comment by antonio-rojas** [comment]
The missing symbol `_ZNK2H57DataSet6extendEPKy` (aka `H5::DataSet::extend(unsigned long long const*) const`) comes from hdf5lib. Have you rebuilt that?

**Comment by starsareintherose** [comment]
rebuild yesterday https://github.com/BioArchLinux/Packages/blob/master/BioArchLinux/r-rhdf5lib/PKGBUILD

**Comment by antonio-rojas** [comment]
Are the built packages available somewhere?

**Comment by starsareintherose** [comment]
right https://github.com/BioArchLinux/Packages/blob/master/BioArchLinux/r-mzR/lilac.yaml include this package, it means that it can install the package in the latest version from this repository.

**Comment by antonio-rojas** [comment]
OK, it turns out my r fix was incomplete. It was only setting CFLAGS, which didn't work for C++ packages. It should be fine with r 4.2.0-3.

**Comment by starsareintherose** [comment]
okay, thanks
