### ISSUE TITLE
Please add following PKGs

### ISSUE THREAD

**Issue by llity** [BioArchLinux/Packages#62]
**Information**
 - Package Name: [RSeQC]
 - Can it directly run on Linux: [yes]
 - Can it run on the wine: [not]
 -  Website: http://rseqc.sourceforge.net/
 - Download URL: http://rseqc.sourceforge.net/#download-rseqc
 - Package description: RSeQC package provides a number of useful modules that can comprehensively evaluate high throughput sequence data especially RNA-seq data. Some basic modules quickly inspect sequence quality, nucleotide composition bias, PCR bias and GC bias, while RNA-seq specific modules evaluate sequencing saturation, mapped reads distribution, coverage uniformity, strand specificity, transcript level RNA integrity etc.

**Information**
 - Package Name: [[CIRCexplorer](http://yanglab.github.io/CIRCexplorer/)]
 - Can it directly run on Linux: [yes]
 - Can it run on the wine: [not]
 -  Website: https://circexplorer2.readthedocs.io/en/latest/
 - Download URL: http://yanglab.github.io/CIRCexplorer/
 - Package description: CIRCexplorer is a combined strategy to identify junction reads from back spliced exons and intron lariats.

**Information**
 - Package Name: [ucsc_edu_admin_exe] Just a native program
 - Can it directly run on Linux: [yes]
 - Can it run on the wine: [not]
 -  Website: http://hgdownload.soe.ucsc.edu/admin/exe/
 - Download URL: http://hgdownload.soe.ucsc.edu/admin/exe/
 - Package description:

**Information**
 - Package Name: [[TACO](http://tacorna.github.io/)]
 - Can it directly run on Linux: [yes]
 - Can it run on the wine: [not]
 -  Website: http://tacorna.github.io/
 - Download URL: http://tacorna.github.io/
 - Package description: TACO: Multi-sample transcriptome assembly from RNA-Seq

**Popularity**
 - Number of citations from WOS per year: [e.g. 5.6, N/A]
 - Research interests in ResearchGate: [e.g. 0.1, N/A]
 - Any other reason:

**Comment by sukanka** [comment]
Hello, `RSeQC` and `CIRCexplorer` have been added, and are known as `rseqc` and `circexplorer` respectively.

But `taco` and `ucsc_edu_admin_exe` can't be built, see 
https://github.com/tacorna/taco/issues/14
and
[ucsc-genome-browser-434_preview2-1-x86_64-build.log](https://github.com/BioArchLinux/Packages/files/9126104/ucsc-genome-browser-434_preview2-1-x86_64-build.log)

**Comment by starsareintherose** [comment]
I see it would need to build java things in ucsc_edu_admin_exe, it's difficult, maybe just add binary.

For tacorna, maybe just binary like what bioconda did

**Comment by sukanka** [comment]
`taco` (known as `taco`)  and `ucsc_edu_admin_exe` (known as `ucsc-genome-browser`) have been added.

**Comment by llity** [comment]
> I see it would need to build java things in ucsc_edu_admin_exe, it's difficult, maybe just add binary.
> 
> For tacorna, maybe just binary like what bioconda did

I just downloaded it, can be used in my pipeline.

**Comment by llity** [comment]
> `taco` (known as `taco`) and `ucsc_edu_admin_exe` (known as `ucsc-genome-browser`) have been added.

Can you reference the taco in the aur?

**Comment by sukanka** [comment]
> Is it possible to reference the taco package in the ananconda?
> 
> <img alt="image" width="582" src="https://user-images.githubusercontent.com/11771112/179770982-0a737617-04a2-456d-80f8-84f9476111fd.png">

Sorry, I didn't get it. You can express it in Chinese.

**Comment by sukanka** [comment]
> 参考anaconda里构建taco的依赖软件来打包taco。https://anaconda.org/bioconda/taco/files

依赖软件，你是指依赖加这几项吗？
```
        - libgcc
        - python
        - pyinstaller
```
个人感觉没必要， `libgcc` 包含在 `base-devel` 里面， `python` `pyinstaller` 是从源码构建才需要的。
我看了文件，也跟 bioconda 里面没有本质区别。
```
➜  ~ pacman -Ql taco 
taco /usr/
taco /usr/bin/
taco /usr/bin/taco_refcomp
taco /usr/bin/taco_run
```

**Comment by llity** [comment]
谢谢！
