### ISSUE TITLE
Please add Tophat and CPC2 pkgs.

### ISSUE THREAD

**Issue by llity** [BioArchLinux/Packages#64]
**Information**
 - Package Name: [Tophat]
 - Can it directly run on Linux: [yes]
 - Can it run on the wine: [not]
 -  Website: https://ccb.jhu.edu/software/tophat/index.shtml
 - Download URL: http://ccb.jhu.edu/software/tophat/downloads
 - Package description: TopHat is a fast splice junction mapper for RNA-Seq reads.

**Information**
 - Package Name: [CPC2]
 - Can it directly run on Linux: [yes]
 - Can it run on the wine: [not]
 -  Website: http://cpc2.gao-lab.org/
 - Download URL: http://cpc2.gao-lab.org/download.php
 - Package description: Coding Potential Calculator distinguishes protein-coding from non-coding RNAs based on the sequence features of the input transcripts.

**Popularity**
 - Number of citations from WOS per year: [e.g. 5.6, N/A]
 - Research interests in ResearchGate: [e.g. 0.1, N/A]
 - Any other reason:

**Comment by sukanka** [comment]
add tophat https://github.com/BioArchLinux/Packages/commit/d4be81b52d81ed2a6028ac18d44393ee101777d3

**Comment by llity** [comment]
> add tophat [d4be81b](https://github.com/BioArchLinux/Packages/commit/d4be81b52d81ed2a6028ac18d44393ee101777d3)

I cannot find tophat tool. Please check it.

Thanks

**Comment by sukanka** [comment]
> I cannot find tophat tool. Please check it.
> 
> Thanks

which mirror do you use? You can find it in the main repository (repo.bioarchlinux.org), for other mirrors, it might take hours or days for them to sync with repo.bioarchlinux.org
```
➜  ~ sudo pacman -Syy
➜  ~ pacman -Ss tophat
bioarchlinux/tophat 2.1.2-1
    fast splice junction mapper for RNA-Seq reads
```

**Comment by starsareintherose** [comment]
could you show us the mirror you used for bioarchlinux repository, could you show you `/etc/pacman.conf`?

**Comment by starsareintherose** [comment]
njupt mirror haven't sync these packages

**Comment by llity** [comment]
Thanks.

**Comment by starsareintherose** [comment]
now it is synced
