### ISSUE TITLE
[FEELnc, assemblyline] 打包请求，后面为Python软件，不知道能否打包。

### ISSUE THREAD

**Issue by llity** [BioArchLinux/Packages#65]
**Information**
 - Package Name: [FEELnc]
 - Can it directly run on Linux: [yes]
 - Can it run on the wine: [not]
 -  Website: https://github.com/tderrien/FEELnc
 - Download URL: https://github.com/tderrien/FEELnc/releases/tag/v.0.2.1
 - Package description: FlExible Extraction of Long non-coding RNAs.

**Information**
 - Package Name: [assemblyline] --Python 软件能打包吗？
 - Can it directly run on Linux: [yes]
 - Can it run on the wine: [not]
 -  Website: https://github.com/bmpvieira-forks/assemblyline
 - Download URL: https://github.com/bmpvieira-forks/assemblyline/tree/master/assemblyline
 - Package description: AssemblyLine: transcriptome meta-assembly from RNA-Seq.
 
谢谢！

**Popularity**
 - Number of citations from WOS per year: [e.g. 5.6, N/A]
 - Research interests in ResearchGate: [e.g. 0.1, N/A]
 - Any other reason:

**Comment by starsareintherose** [comment]
add python2-assemblyline a49c22dc16642def4bdc165d652eda0d87738181

**Comment by starsareintherose** [comment]
[FEELnc](https://github.com/tderrien/FEELnc) depends
- [ ] bioperl & perl
- [ ] r-randomForest, r-rocr & r
- [ ] [perl-parallel-forkmanager](https://metacpan.org/dist/Parallel-ForkManager)
- [ ] https://github.com/rizkg/KmerInShort
- [ ] https://github.com/agordon/fasta_ushuffle
- [ ] https://github.com/s-will/ushuffle

**Comment by hubutui** [comment]
python2 的包不建议再继续用了啊，看了一下 github repo，这是 8 年前最后更新的了。改换新的替代品了。

**Comment by starsareintherose** [comment]
> python2 的包不建议再继续用了啊，看了一下 github repo，这是 8 年前最后更新的了。改换新的替代品了。

FEELnc depnds on it and ...

**Comment by llity** [comment]
> python2 的包不建议再继续用了啊，看了一下 github repo，这是 8 年前最后更新的了。改换新的替代品了。

确实很多软件还在py2下使用的🙏

**Comment by starsareintherose** [comment]
> python2 的包不建议再继续用了啊，看了一下 github repo，这是 8 年前最后更新的了。改换新的替代品了。

生物人的痛你不懂哈哈哈哈

**Comment by sukanka** [comment]
其实可以用 2to3转换到python3

**Comment by llity** [comment]
> add python2-assemblyline a49c22dc16642def4bdc165d652eda0d87738181

谢谢，软件调用位置在哪里呢

**Comment by sukanka** [comment]
> 谢谢，软件调用位置在哪里呢

没有调用位置，你可以使用 如下命令查看
```
pacman -Ql python2-assemblyline 
```
另外 feelnc 已经添加， https://github.com/BioArchLinux/Packages/commit/b4b233da83544f5d497e2a6460f2dc661149aab2

**Comment by llity** [comment]
> > 谢谢，软件调用位置在哪里呢
> 
> 
> 
> 没有调用位置，你可以使用 如下命令查看
> 
> ```
> 
> pacman -Ql python2-assemblyline 
> 
> ```
> 
> 另外 feelnc 已经添加， https://github.com/BioArchLinux/Packages/commit/b4b233da83544f5d497e2a6460f2dc661149aab2
> 
> 

谢谢，用别忙引用

**Comment by sukanka** [comment]
FEELnc now available as `feelnc`, see https://build.bioarchlinux.org/logs.html
