### ISSUE TITLE
[REQUEST torque pkg] 这个包在aur已经失效

### ISSUE THREAD

**Issue by llity** [BioArchLinux/Packages#69]
**Information**
 - Package Name: [torque]
 - Can it directly run on Linux: [yes]
 - Can it run on the wine: [not]
 -  Website: https://adaptivecomputing.com/cherry-services/moab-nodus-cloud-bursting/
 - Download URL: https://github.com/adaptivecomputing/torque/tree/6.1.3.h2
 - Package description: Resource management system for submitting and controlling jobs on supercomputers, clusters, and grids.
 - DOI:
 

**Popularity**
 - Number of citations from WOS per year: [e.g. 5.6, N/A]
 - Research interests in ResearchGate: [e.g. 0.1, N/A]
 - Any other reason:

**Comment by sukanka** [comment]
> As of June 2018, Adaptive Computing is offering TORQUE and TORQUE Support for purchase.

>Now you need to provide the source file yourself to build this package.

**Comment by sukanka** [comment]
在 github找到了 https://github.com/adaptivecomputing/torque/tree/6.1.3.h5

**Comment by llity** [comment]
> 在 github找到了 [adaptivecomputing/torque@`6.1.3.h5`](https://github.com/adaptivecomputing/torque/tree/6.1.3.h5)

对的，能找到，完全open source。

**Comment by sukanka** [comment]
但是这个无法构建了，我无法修复它，它也和 bio 无关。

**Comment by starsareintherose** [comment]
So sorry, if we build it, based on the license, we must use the commercial company's name to describe it. Secondly, the upstream code is unfriendly, but it's okay if someone helps. The most essential point is that this is not biology-related and you haven't fulfilled any reason under `Popularity` .

Therefore, closed, so sorry. But still welcome any bio-related packages request.

**Comment by hubutui** [comment]
这不是那个集群上用来提交任务的么？还有人用 torque？我见大部分都是 slurm，或者 pbs。

**Comment by llity** [comment]
> 这不是那个集群上用来提交任务的么？还有人用 torque？我见大部分都是 slurm，或者 pbs。

能打个slurm的包吗？

**Comment by sukanka** [comment]
> 能打个slurm的包吗？

这种请求其实提交给 Arch4edu 或者 ArchlinuxCN 更合适。

**Comment by llity** [comment]
> slurm

学校任务提交就是用的torque哦

**Comment by hubutui** [comment]
aur 上就有 slurm 啊，https://aur.archlinux.org/packages/slurm-llnl。我自己是有打包，然后单击部署玩玩，但是没有加到 archlinuxcn repo 或者这里。

**Comment by starsareintherose** [comment]
> > slurm
> 
> 学校任务提交就是用的torque哦

我觉得你需要考虑一个问题，就是如果你只是 follow 学校，那你的未来可能会面临一定风险

请参阅 https://blog.malacology.net/posts/codeman/

**Comment by alienzj** [comment]
> > 这不是那个集群上用来提交任务的么？还有人用 torque？我见大部分都是 slurm，或者 pbs。
> 
> 能打个slurm的包吗？

https://wiki.archlinux.org/title/Slurm
