### ISSUE TITLE
[BUG] r-herper: upstream bug

### ISSUE THREAD

**Issue by sukanka** [BioArchLinux/Packages#76]
**Log of the bug**
`r-herper` failed to build.  It has been fixed in the [GitHub repo](https://github.com/RockefellerUniversity/Herper/commit/0ce7fa1a99e2b02878dbcb93fd1b6fafb9ae7f3a) but not in [Bioconductor](https://bioconductor.org/packages/release/bioc/html/Herper.html). 
It will be ok automatically in the next release. 

I think we don't need to fix it manually.

<details>

```
* installing *source* package ‘Herper’ ...
** using staged installation
Error : Invalid DESCRIPTION file

Authors@R field gives more than one person with maintainer role:
  Matt Paul <mpaul@rockefeller.edu> [aut, cre] (<https://orcid.org/0000-0002-3020-7729>)
  Thomas Carroll <tc.infomatics@gmail.com> [aut, cre] (<https://orcid.org/0000-0002-0073-1714>)

See section 'The DESCRIPTION file' in the 'Writing R Extensions'
```
 
 </details>

**Desktop (please complete the following information):**
 - Desktop Enviroment: [e.g. gnome, kde, server]
 - Linux Kernel: [e.g. linux-lts 5.10.60-1]
 - Package Version: [e.g. 22]

**Additional context**

**Comment by starsareintherose** [comment]
the R package is git version!

**Comment by starsareintherose** [comment]
4fa4493eecb92745a4da5d6a06e23de2c339e9f0

**Comment by sukanka** [comment]
> the R package is git version!

Since it is git version and it's named `r-herper` rather than `r-herper-git`, it should not be pushed to aur.
By the way the current version number is incorrect. It's 1.7.1 , see https://github.com/RockefellerUniversity/Herper/blob/master/DESCRIPTION

**Comment by starsareintherose** [comment]
fixed the ver update here d1841d87ff0d7123a1b39522371783478abf90ef
and for changing the name, it's not necessary, because when the version is updated, lilac will notice it and update AUR. There are a lot of AUR in git is pushed to AUR

**Comment by sukanka** [comment]
> for changing the name, it's not necessary, because when the version is updated, lilac will notice it and update AUR. There are a lot of AUR in git is pushed to AUR

Though it's updated, but when there is a new commit ( not a new version), lilac won't update it, however, users from aur will build the package with the new commit. 
So I think we should use specific commit, and there should be a way to updated these commits automatically (in `lilac.py`). 

Packages (this package, and many other packages) pushed to aur should follow this rule. See https://wiki.archlinux.org/title/VCS_package_guidelines#Guidelines

**Comment by starsareintherose** [comment]
but we need to update the pkgver and then user will know it

**Comment by sukanka** [comment]
> but we need to update the pkgver and then user will know it

I mean, what will happen if there are some new commits between two different `pkgver`, and a user happens to build the package?

**Comment by starsareintherose** [comment]
give patch? just like what you did for r-openmx? maybe patch the name? for all R packages in git?
