### ISSUE TITLE
[BUG] `r-chemmineob` failed to build 

### ISSUE THREAD

**Issue by sukanka** [BioArchLinux/Packages#77]
Upstream bug, see https://github.com/openbabel/openbabel/pull/2493
and https://bugs.archlinux.org/task/75634?project=1&string=openbabel
**Log of the bug**

<details>

```
In file included from ChemmineOB.cpp:1569:
/usr/include/openbabel3/openbabel/obutil.h: In member function ‘void OpenBabel::OBStopwatch::Start()’:
/usr/include/openbabel3/openbabel/obutil.h:65:14: error: ‘clock’ was not declared in this scope
   65 |       start= clock();
      |              ^~~~~
```
 
 </details>

**Desktop (please complete the following information):**
 - Desktop Enviroment: [e.g. gnome, kde, server]
 - Linux Kernel: [e.g. linux-lts 5.10.60-1]
 - Package Version: [e.g. 22]

**Additional context**

**Comment by starsareintherose** [comment]
upstream fixed
