### ISSUE TITLE
[BUG] Build failure due to `r-matrix` update

### ISSUE THREAD

**Issue by sukanka** [BioArchLinux/Packages#78]
Recently, `r-matrix` was updated from `1.4.1` to `1.5.0`. But [`r`](https://archlinux.org/packages/community/x86_64/r/) still provides `r-matrix=1.4.1`, which make packages that require `r-matrix>=1.5.0`  fail to be built. 
It's an upstream issue since `r-matrix` is a built-in module of `r`, maybe it will be updated when `r` 4.3.0 is released.

The packages are listed below

- [ ] [`r-gsva`](https://build.bioarchlinux.org/api/pkg/r-gsva/log/1663805058)
- [ ] [`r-sctransform`](https://build.bioarchlinux.org/api/pkg/r-sctransform/log/1663783269)
- [ ] [`r-seuratobject`](https://build.bioarchlinux.org/api/pkg/r-seuratobject/log/1663696919)
- [ ] [`r-matrixmodels`](https://build.bioarchlinux.org/api/pkg/r-matrixmodels/log/1662897665)
- [ ] [`r-delayedmatrixstats`](https://build.bioarchlinux.org/api/pkg/r-delayedmatrixstats/log/1664409697)
- [ ] [`r-fgarch`](https://build.bioarchlinux.org/api/pkg/r-fgarch/log/1664453018)

The following packages fail to be built as they depend on the packages above
- [ ] [`r-seurat`](https://build.bioarchlinux.org/api/pkg/r-seurat/log/1663804979)
- [ ] [`r-jaspequivalencettests`](https://build.bioarchlinux.org/api/pkg/r-jaspequivalencettests/log/1662984529)
- [ ] `r-jaspanova`
- [ ] `r-jaspnetwork`
- [ ] `r-jaspfrequencies`
- [ ] `r-jaspmixedmodels`
- [ ] `r-jaspdistributions`
- [ ] `r-jasplearnbayes`
- [ ] `r-jaspttests`
- [ ] `r-heplots`
- [ ] `r-orthogene`

**Desktop (please complete the following information):**
 - Desktop Enviroment: [e.g. gnome, kde, server]
 - Linux Kernel: [e.g. linux-lts 5.10.60-1]
 - Package Version: [e.g. 22]

**Additional context**

**Comment by starsareintherose** [comment]
solved https://github.com/archlinux/svntogit-community/commit/3765ca233add49017d178527da2ff90ca992f502

**Comment by sukanka** [comment]
complete in ce0ad0649eb73036edd768165263a7188486f2c9
