### ISSUE TITLE
[BUG] Stop removing previous maintainer and contributors from PKGBUILDs

### ISSUE THREAD

**Issue by AladW** [BioArchLinux/Packages#79]
I'm guessing this is because AUR PKGBUILDs are automatically overwritten without checking their previous contents. Either way, this is rude towards previous contributors so you should stop doing it. Example: https://aur.archlinux.org/cgit/aur.git/commit/?h=r-chron&id=813907801e9fc8d142509ccb67adf2de546974fa

**Comment by sukanka** [comment]
You are right. The PKGBUILDS are automatically generated, so previous contents are overwritten. But it is now hard to preserve previous contents as we do not know how many packages suffer from this. 

It is easy to fix this single package, but to add previous contents back for all, we need a full list of package names (about 170 packages).

More precisely, we need a list of `pkgname`s that are maintained but not submitted by BioArchLinuxBot.
With [AUR rpc](https://aur.archlinux.org/rpc.php), it is easy to find all packages maintained by the bot, but it does not support search by the submitter.

Could you help us with that?

**Comment by AladW** [comment]
> Could you help us with that?

Sure: https://gist.github.com/AladW/d524bdbbcd3170303c2337a8278d305d

The list includes all packages which were submitted before the creation of `BioArchlinuxBot`. It doesn't include those submitted by other accounts after `BioArchlinuxBot` was created, but it seems to cover most candidates (152).

**Comment by sukanka** [comment]
> The list includes all packages which were submitted before the creation of `BioArchlinuxBot`. 

Thanks for your list, it helps me a lot! I'm now fixing them one by one.
> It doesn't include those submitted by other accounts after `BioArchlinuxBot` was created, but it seems to cover most candidates (152).

Maybe another way is to find all packages submitted by other accounts before `BioArchlinuxBot` submitted its first package. This should cover all candidates.

**Comment by sukanka** [comment]
Hello, is the pr https://github.com/BioArchLinux/Packages/pull/81 enough for this issue? Or you would like to help us by providing the full lists?

**Comment by starsareintherose** [comment]
It seems that we need bump pkgrel to push to aur

**Comment by AladW** [comment]
Thank you very much for the quick fix. I'll take a look later if I can find the remaining packages.

**Comment by AladW** [comment]
I didn't have the chance to look at this yet. However, I've submitted https://gitlab.archlinux.org/archlinux/aurweb/-/issues/400

Feel free to close this in favor of #81 and I can file a PR with the remaining packages at some later point.

**Comment by AladW** [comment]
Here's the list of remaining packages:
```
diamond
r-biglm
r-cnorm
r-collections
r-compquadform
r-fastmatch
r-feather
r-gbrd
r-grohmm
r-here
r-languageserver
r-leaps
r-mitools
r-r.cache
r-rcpptoml
r-reticulate
r-rgeos
r-slam
r-styler
r-survey
```

**Comment by sukanka** [comment]
> Here's the list of remaining packages:

I will be extremely busy in the next two weeks, so a pr is welcome.

**Comment by sukanka** [comment]
All others (except `diamond`) are fixed in https://github.com/BioArchLinux/Packages/commit/23c33d455fa4010c6ab3edb85847cd17e194a5f1.
The case for `diamond` is quite complex,  @starsareintherose  is required to deal with `diamond`, a relevant comment is in https://github.com/BioArchLinux/Packages/pull/90#issuecomment-1301602250

**Comment by starsareintherose** [comment]
I think I already get diamond into python-diamond, see [AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-diamond), no information is lost.

**Comment by sukanka** [comment]
> I think I already get diamond into python-diamond, see [AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-diamond), no information is lost.
But there is a severe issue with that action. 
* Users of the original diamond (`python-diamond`) may feel confused, 
* The `pkgver` downgraded from `4.0.515` to `2.0.15`, but `epoch` was not increased.
* There may be other users that wonder why the previous maintainer information gets lost and may open an issue.
