### ISSUE TITLE
JASP desktop upgrade reminder

### ISSUE THREAD

**Issue by shun2wang** [BioArchLinux/Packages#80]
Hello @sukanka  and team

你好 Sukanka
我是 JASP 团队成员。我们注意到你正在Arch上构建 JASP，非常**感谢**你（和你的团队）长期为此提供维护。我尝试通过邮件提醒了你，但更好的办法可能是在这里一个备忘录来更新。在此提醒你我们释放了新的版本（[0.16.4](https://github.com/jasp-stats/jasp-desktop/releases/tag/v0.16.4)）。
我们感激你的付出。

I am a JASP team member. We noticed that you are building JASP on Arch, and thank you (and your team) for maintaining this on a long-term basis. I tried emailing to let you know, but a better way might be to update a note here, We released a new version ([0.16.4](https://github.com/jasp-stats/jasp-desktop/releases/tag/v0.16.4)).
We appreciate that.

cheers,
Shun

**Comment by sukanka** [comment]
啊，原来6天前就出新版本了呀，谢谢提醒，会尽快更新的

**Comment by sukanka** [comment]
原来这个是因为依赖关系不满足才构建失败了，参见 [jasp-desktop的构建日志](https://build.bioarchlinux.org/api/pkg/jasp-desktop/log/1664474668)，它需要 `r-matrixmodels`，而
[`r-matrixmodels`](https://build.bioarchlinux.org/api/pkg/r-matrixmodels/log/1662897665) 需要 `r-matrix>=1.4.2`（`r-matrix`最近[更新了](https://cran.r-project.org/web/packages/Matrix/index.html)） 但是由于 `r-matrix` 是 `r` 的内置组件，目前只有 `1.4.1`，需要等 `r` 更新了之后才会更新。

我试试能不能手动移包吧。

**Comment by sukanka** [comment]
complete in https://github.com/BioArchLinux/Packages/commit/517274d3b296790493424d9e1cc732d478980bf2

**Comment by shun2wang** [comment]
Now all JASP module repo also have version tags so you can set build bot to build automatically.

**Comment by sukanka** [comment]
> Now all JASP module repo also have version tags so you can set build bot to build automatically.

So cool! We will start to use these tags soon. Thanks!

**Comment by sukanka** [comment]
I'm confused about the version of [jaspTools](https://github.com/jasp-stats/jaspTools), in `DESCRIPTION` file, its version is 1.5.1, but its latest tag is 0.17.0. Is that OK?

**Comment by shun2wang** [comment]
I think should follow the tag because jaspTools is not a analysis module but a basic tool. and we don't have develop branch on it so Im not suggest follow the version number.

This seems to contradict the philosophy of archlinux, but I don't want you to follow the new develop version.

**Comment by sukanka** [comment]
> I think should follow the tag because jaspTools is not a analysis module but a basic tool. and we don't have develop branch on it so Im not suggest follow the version number.
> 
> This seems to contradict the philosophy of archlinux, but I don't want you to follow the new develop version.

OK, then we will follow the tag. Since `vercmp 0.14.0 1.5.1` returns -1, which means it's a downgrade,  we have to add an epoch to the version number, so it's taken as an upgrade.
