### ISSUE TITLE
[REQUEST] Add ProtHint

### ISSUE THREAD

**Issue by kbipinkumar** [BioArchLinux/Packages#88]
**Information**
 - Package Name: ProtHint
 - Can it directly run on Linux: yes
 - Can it run on the wine: N/A
 -  Website: https://github.com/gatech-genemark/ProtHint
 - Download URL: https://github.com/gatech-genemark/ProtHint/releases
 - Package description: ProtHint is a pipeline for predicting and scoring hints (in the form of introns, start and stop codons) in the genome of interest by mapping and spliced aligning predicted genes to a database of reference protein sequences
 - DOI: 10.1093/nargab/lqaa026
 

**Popularity**
 - Number of citations in google scholar: ~101 in last three years
 - Any other reason: this package is mandatory for Braker2 pipeline used for automatic eukaryotic genome annotation (https://doi.org/10.1093/nargab/lqaa108)

**Comment by sukanka** [comment]
I just added the PKGBUILD, https://github.com/BioArchLinux/Packages/commit/436f263f484dab0a6b8ee31ee31bd71061069e03, but additional effort is needed (some perl modules), assigned to @starsareintherose 
- [ ]  [perl-math-utils](https://aur.archlinux.org/packages/perl-math-utils)
- [ ]  [perl-mce](https://aur.archlinux.org/packages/perl-mce)
- [ ]  [perl-threads](https://metacpan.org/pod/threads)
