### ISSUE TITLE
any plan to make a subfoulder to store the package PKGBUILD?

### ISSUE THREAD

**Issue by hubutui** [BioArchLinux/Packages#9]
It seems now it's [arch4edu](https://github.com/arch4edu/arch4edu) style. If more packages are added, users have to scroll a long way to read the README.md in github repo. See also [ArchLinuxCN repo](https://github.com/archlinuxcn/repo).

**Comment by starsareintherose** [comment]
okay, I plan to change these days, and reconfigure the server for this change

**Comment by starsareintherose** [comment]
solved now
