### ISSUE TITLE
[MAINTAIN] packages influenced by openssl

### ISSUE THREAD

**Issue by starsareintherose** [BioArchLinux/Packages#93]
**Packages List**

<details>

- [x] htslib-1.16-2: usr/lib/htslib/plugins/hfile_s3.so (libcrypto.so.1.1
- [x] phylosuite-1.2.2-5: usr/bin/phylosuite/libssl.so.1.1 (libcrypto.so.1.1)
- [x] python2-2.7.18-4: usr/lib/python2.7/lib-dynload/_ssl.so (libssl.so.1.1)
- [x] qt4-4.8.7-40: usr/lib/libQtNetwork.so.4.8.7 (libssl.so.1.1)
- [x] r-hdf5array-1.26.0-1: usr/lib/R/library/HDF5Array/libs/HDF5Array.so (libcrypto.so.1.1)
- [x] r-openssl-2.0.4-1: usr/lib/R/library/openssl/libs/openssl.so (libssl.so.1.1)
- [x] r-rhdf5-2.42.0-1: usr/lib/R/library/rhdf5/libs/rhdf5.so (libcrypto.so.1.1)
- [x] r-rserve-1.8.10-4: usr/lib/R/library/Rserve/libs/Rserve.so (libssl.so.1.1)
- [x] r-s2-1.1.0-2: usr/lib/R/library/s2/libs/s2.so (libcrypto.so.1.1)
- [x] seqlib-1.2.0-3: usr/bin/seqtools (libcrypto.so.1.1)
- [x] shapeit4-4.2.2-3: usr/bin/shapeit4 (libssl.so.1.1)

 </details>

**Packages (please complete the following information):**
 - Package Name: [e.g. iqtree]

**Description**

**Comment by starsareintherose** [comment]
略略略

**Comment by sukanka** [comment]
fixed in https://github.com/BioArchLinux/Packages/commit/92aaedc53255f29e9fac5daf22b5f150ccafec66
